const $ = (id) => document.getElementById(id);
let lastRows = [];
let lastSummary = null;

const aliases = {
  sku: ["sku", "product_sku", "รหัสสินค้า", "รหัส"],
  name: ["product_name", "product", "name", "ชื่อสินค้า", "สินค้า"],
  stock: ["stock_qty", "stock", "qty", "quantity", "on_hand", "คงเหลือ", "จำนวนคงเหลือ"],
  cost: ["unit_cost", "cost", "cost_price", "ต้นทุน", "ต้นทุนต่อหน่วย"],
  sold: ["sold_30d", "units_sold_30d", "sales_qty_30d", "sold30", "ขาย30วัน", "ยอดขาย30วัน"]
};
function norm(s){return String(s||"").trim().toLowerCase().replace(/\s+/g,"_")}
function parseCSV(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&n==="\n")i++;row.push(cell);if(row.some(x=>String(x).trim()!==""))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>String(x).trim()!==""))rows.push(row);return rows}
function findCol(headers,key){const normalized=headers.map(norm);for(const alias of aliases[key]){const i=normalized.indexOf(norm(alias));if(i>=0)return i}return-1}
function num(v){const n=Number(String(v??"").replace(/[฿,$\s]/g,""));return Number.isFinite(n)?n:0}
function money(v){return new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",maximumFractionDigits:0}).format(v||0)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function classify(stock,sold,watch,slow,dead){if(stock<=0)return{label:"HEALTHY",cls:"healthy",days:0,action:"ไม่มีสต๊อกค้าง"};if(sold<=0)return{label:"DEAD",cls:"dead",days:Infinity,action:"หยุดซื้อ / เคลียร์ / Bundle"};const days=stock/(sold/30);if(days>=dead)return{label:"DEAD",cls:"dead",days,action:"หยุดซื้อ / Clearance"};if(days>=slow)return{label:"SLOW",cls:"slow",days,action:"ชะลอ Reorder / ทำโปรเฉพาะ SKU"};if(days>=watch)return{label:"WATCH",cls:"watch",days,action:"ติดตามอีก 30 วัน"};return{label:"HEALTHY",cls:"healthy",days,action:"คงแผนเดิม"}}
function analyze(text){const rows=parseCSV(text.replace(/^\uFEFF/,""));if(rows.length<2)throw new Error("ไม่พบข้อมูลใน CSV");const headers=rows[0];const idx={sku:findCol(headers,"sku"),name:findCol(headers,"name"),stock:findCol(headers,"stock"),cost:findCol(headers,"cost"),sold:findCol(headers,"sold")};const missing=Object.entries(idx).filter(([,v])=>v<0).map(([k])=>k);if(missing.length)throw new Error("คอลัมน์ไม่ครบ: "+missing.join(", ")+" — ดาวน์โหลด Sample CSV เพื่อดูรูปแบบ");const watch=num($("watchDays").value),slow=num($("slowDays").value),dead=num($("deadDays").value);if(!(watch<slow&&slow<dead))throw new Error("Threshold ต้องเรียง Watch < Slow < Dead");const rank={DEAD:0,SLOW:1,WATCH:2,HEALTHY:3};lastRows=rows.slice(1).map(r=>{const stock=num(r[idx.stock]),sold=num(r[idx.sold]),cost=num(r[idx.cost]),c=classify(stock,sold,watch,slow,dead);return{priority:c.label,cls:c.cls,sku:r[idx.sku]||"",name:r[idx.name]||"",stock,sold,cost,days:c.days,value:stock*cost,action:c.action}}).filter(x=>x.sku||x.name).sort((a,b)=>rank[a.priority]-rank[b.priority]||b.value-a.value);render()}
function render(){const dead=lastRows.filter(x=>x.priority==="DEAD"),slow=lastRows.filter(x=>x.priority==="SLOW"),inv=lastRows.reduce((s,x)=>s+x.value,0),trapped=[...dead,...slow].reduce((s,x)=>s+x.value,0);lastSummary={trapped,dead:dead.length,slow:slow.length,inv,total:lastRows.length};$("trappedCapital").textContent=money(trapped);$("deadCount").textContent=dead.length;$("slowCount").textContent=slow.length;$("inventoryValue").textContent=money(inv);$("resultBody").innerHTML=lastRows.slice(0,100).map(x=>`<tr><td><span class="badge ${x.cls}">${x.priority}</span></td><td>${esc(x.sku)}</td><td>${esc(x.name)}</td><td>${x.stock}</td><td>${x.sold}</td><td>${Number.isFinite(x.days)?Math.round(x.days):"∞"}</td><td>${money(x.value)}</td><td>${esc(x.action)}</td></tr>`).join("");$("results").classList.remove("hidden");$("errorBox").classList.add("hidden");$("results").scrollIntoView({behavior:"smooth",block:"start"});window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:"dead_stock_scan_complete",dead_sku:dead.length,slow_sku:slow.length,trapped_capital:Math.round(trapped)})}
function showErr(e){$("errorBox").textContent=e.message||String(e);$("errorBox").classList.remove("hidden");$("results").classList.add("hidden")}
function handleFile(file){if(!file)return;$("fileName").textContent=file.name;const reader=new FileReader();reader.onload=()=>{try{analyze(reader.result)}catch(e){showErr(e)}};reader.onerror=()=>showErr(new Error("อ่านไฟล์ไม่สำเร็จ"));reader.readAsText(file,"utf-8")}
function downloadBlob(name,text){const blob=new Blob(["\uFEFF"+text],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
function downloadSample(){const sample=["sku,product_name,stock_qty,unit_cost,sold_30d","A100,เสื้อยืดสีดำ,120,95,4","A101,หมวกแก๊ป,80,120,0","A102,แก้วน้ำ,25,70,18","A103,กระเป๋าผ้า,65,55,8","A104,ถุงเท้า,200,28,90"].join("\n");downloadBlob("dead_stock_sample.csv",sample);window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:"dead_stock_sample_download"})}
$("chooseFile").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>handleFile(e.target.files[0]);$("downloadSampleTop").onclick=downloadSample;$("downloadSampleBottom").onclick=downloadSample;
const dropZone=$("dropZone");["dragenter","dragover"].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.classList.add("drag")}));["dragleave","drop"].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.classList.remove("drag")}));dropZone.addEventListener("drop",e=>handleFile(e.dataTransfer.files[0]));
$("downloadReport").onclick=()=>{if(!lastRows.length)return;const header=["priority","sku","product_name","stock_qty","sold_30d","days_cover","inventory_cost_value","recommended_action"];const csvRows=lastRows.map(x=>[x.priority,x.sku,x.name,x.stock,x.sold,Number.isFinite(x.days)?Math.round(x.days):"INF",Math.round(x.value),x.action].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(","));downloadBlob("dead_stock_action_queue.csv",[header.join(","),...csvRows].join("\n"));window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:"dead_stock_report_download"})};
$("copySummary").onclick=async()=>{if(!lastSummary)return;const summary=["Dead Stock Scan",`เงินจมโดยประมาณ: ${money(lastSummary.trapped)}`,`Dead SKU: ${lastSummary.dead}`,`Slow SKU: ${lastSummary.slow}`,`มูลค่าสต๊อกรวม: ${money(lastSummary.inv)}`].join("\n");try{await navigator.clipboard.writeText(summary);$("copySummary").textContent="คัดลอกแล้ว ✓";setTimeout(()=>{$("copySummary").textContent="คัดลอกสรุป"},1500)}catch{alert(summary)}};